# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "../bash/docker_install.sh"

  config.vm.define :centos7 do |c|
    c.vm.box = "centos/7"
  end

  config.vm.define :xenial do |u|
    u.vm.box = "ubuntu/xenial64"
  end
end
