forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/stdlib',
    :git => "https://github.com/puppetlabs/puppetlabs-stdlib",
    :ref => "4.12.0"

mod 'puppetlabs/aws',
    :git => "https://github.com/puppetlabs/puppetlabs-aws",
    :ref => "ef244e5a19788fa6c7c10e57dd2cd88b2aaa5244"
    
#mod 'rancherlabs/rancher_infra',
#    :git => "https://github.com/nrvale0/puppet-rancher_infra",
#    :ref => "os-matrix-phase3"
